# Github action to build the base container and publish it to the GitHub Container Registry (ghcr.io).
# This action is triggered by push to the `main` branch and is designed to run on a
# large github runner with a set of predefined steps.

name: Build Base Container and Publish to GHCR

on:
  push:
    branches: [main, saikatdas0790/devcontainer-image-for-ci]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-builder-base

jobs:
  build-and-push:
    runs-on: large-runner-8c-32m
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          subfolder: .devcontainer/ci-build
          imageName: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          cacheFrom: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          push: always
          # runCmd: |
          # cargo leptos build --release --lib-features release-lib --bin-features release-bin
