name: nightwatch tests
on:
  pull_request:
    branches: main
jobs:
  tests:
    name: "nightwatch tests"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "22.x"

      - name: Install dependencies
        run: |
          cd tests/e2e
          npm ci

      - name: Run Nightwatch tests
        run: |
          cd tests/e2e
          xvfb-run --auto-servernum npm test -- --env chrome --serial
        env:
          PREVIEW_URL: https://pr-${{github.event.number}}-go-bazzinga-hot-or-not-web-leptos-ssr.fly.dev
