name: Generate lighthouse test report on PR
on:
    push:
      branches: [ lighthouse_testing_pipeline ]
    pull_request:
        branches: [ main ]
    # paths:
    #     - "estate_dao_nft/**"

jobs:
    build-check:
        runs-on: ubuntu-latest
        env: 
            COOKIE_KEY: '1267b291500365c42043e04bc69cf24a31495bd8936fc8d6794283675e288fad755971922d45cf1ca0b438df4fc847f39cb0b2aceb3a45673eff231cddb88dc9'

        steps:
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Rust Setup
            uses: dtolnay/rust-toolchain@master
            with:
                toolchain: "nightly"
                targets: "x86_64-unknown-linux-musl,wasm32-unknown-unknown"
                components: "clippy,rustfmt"

          - uses: cargo-bins/cargo-binstall@main
          - name: cargo-leptos setup
            run: cargo binstall --no-confirm cargo-leptos --version 0.2.16

          - name: Cache rust dependencies and build output
            uses: Swatinem/rust-cache@v2

          - name: Install Node.js
            uses: actions/setup-node@v4
            with: 
                node-version: 20
          - run: npm install

          - name: Install Lighthouse
            run: npm install -g @lhci/cli@0.13.x

          - name: Run Lighthouse
            run: lhci autorun

          - uses: peter-evans/sticky-pull-request-comment@v2
            with:
              GITHUB_TOKEN: ${{ secrets.LIGHTHOUSE_BOT_TOKEN }}
              number-of-comments: 1 # Creates or updates a single comment
              comment-title: Lighthouse CI Results 
              comment-template: | 
                [View the full report]({{ lighthouse.reportURL }})


