name: Generate lighthouse test report on PR
on:
    pull_request:
        branches: [ main, lighthouse_testing_pipeline ]
        
jobs:
    lhci:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Install Node.js
            uses: actions/setup-node@v4
            with: 
                node-version: 20
          - run: npm install

          # - name: Install Lighthouse
          #   run: npm install -g @lhci/cli@0.13.x

          # - name: Run Lighthouse
          #   run: lhci autorun --upload.githubToken="$LHCI_GITHUB_TOKEN" || echo "LHCI failed!"
          #   env: 
          #       LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

          - name: install playwright
            run: npx playwright install    

          - name: run playwright
            id: tests
            run: npx playwright test --project=firefox 
            continue-on-error: true
        
          # - name: Notify Google Chat on success
          #   if: success()
          #   uses: Co-qn/google-chat-notification@v1
          #   with:
          #     name: test
          #     url: ${{ secrets.TEST_WEBHOOK_URL }}
          #     status: ${{ steps.tests.outcome }}
              
          - name: Notify Google Chat on failure
            uses: Co-qn/google-chat-notification@v1
            with:
              name: test
              url: ${{ secrets.TEST_WEBHOOK_URL }}
              status: ${{ steps.tests.outcome }}

          # using outcome as status
          # - name: Notify Google Chat
          #   uses: google-github-actions/send-google-chat-webhook@v0.0.2
          #   with:
          #     url: ${{ secrets.TEST_WEBHOOK_URL }}
          #     message: ${{ steps.tests.outcome }}

          # - name: Notify Google Chat on success
          #   if: success()
          #   uses: google-github-actions/send-google-chat-webhook@v0.0.2
          #   with:
          #     webhook_url: '${{ secrets.TEST_WEBHOOK_URL }}'
          #     # mention: "<users/all>"
          #     # message: 'Playwright Tests Passed! !!!!!'
          #     status: ${{ steps.tests.outcome }}

          # - name: Notify Google Chat on failure
          #   # if: failure()
          #   uses: google-github-actions/send-google-chat-webhook@v0.0.2
          #   with:
          #     # name: Build
          #     url: ${{ secrets.TEST_WEBHOOK_URL }}
          #     status: ${{ steps.tests.outcome }}

          - name: Check test result and comment
            uses: peter-evans/create-or-update-comment@v1
            with:
              token: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
              issue-number: ${{ github.event.pull_request.number }}
              body: |
                ${{ steps.tests.outcome == 'failed' && 'Test failed, Please check logs for details.' || 'Test passed :heavy_check_mark:'  }}

          - name: Trigger a workflow in another repo
            uses: actions/github-script@v5
            with:
                script: |
                  github.rest.repos.createDispatchEvent({
                    owner: 'shreybaz',
                    repo: 'test_automation',
                    event_type: 'call',
                    client_payload: { key: "value" }
                  });
                github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
