name: Upload secrets to vault

on:
  workflow_dispatch:
  push:
    branches:
      - naitik/coolify-and-vault-integration

permissions:
  id-token: write   
  contents: read

jobs:
  upload-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.yral.com
          method: jwt
          role: hot-or-not-web-leptos-ssr-write-role
          jwtGithubAudience: "https://github.com/dolr-ai"
          exportToken: true
      
      - name: Install Vault CLI
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault

      - name: Set Secrets
        env:
          VAULT_ADDR: https://vault.yral.com
          CLOUDFLARE_STREAM_IMAGES_ANALYTICS_READ_WRITE_SECRET: ${{ secrets.CLOUDFLARE_STREAM_IMAGES_ANALYTICS_READ_WRITE_SECRET }}
          YRAL_DAPP_BACKEND_APP_ADMIN_AND_PROPOSAL_SUBMITTER_IDENTITY_PRIVATE_KEY: ${{ secrets.YRAL_DAPP_BACKEND_APP_ADMIN_AND_PROPOSAL_SUBMITTER_IDENTITY_PRIVATE_KEY }}
          AUTH_SESSION_COOKIE_SIGNING_SECRET_KEY: ${{ secrets.AUTH_SESSION_COOKIE_SIGNING_SECRET_KEY }}
          OFF_CHAIN_AGENT_GRPC_AUTH_TOKEN: ${{ secrets.OFF_CHAIN_AGENT_GRPC_AUTH_TOKEN }}
          HOT_OR_NOT_FEED_INTELLIGENCE_FIREBASE_PROJECT_EVENTS_BQ_SERVICE_ACCOUNT_JSON_FOR_WEB_LEPTOS_SSR_APP: ${{ secrets.HOT_OR_NOT_FEED_INTELLIGENCE_FIREBASE_PROJECT_EVENTS_BQ_SERVICE_ACCOUNT_JSON_FOR_WEB_LEPTOS_SSR_APP }}
          QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
          GOOGLE_ANALYTICS_MEASUREMENT_PROTOCOL_API_SECRET: ${{ secrets.GOOGLE_ANALYTICS_MEASUREMENT_PROTOCOL_API_SECRET }}
          TOKEN_TO_SIGN_OUTGOING_CALLS_TO_NSFW_DETECT_SERVICE: ${{ secrets.TOKEN_TO_SIGN_OUTGOING_CALLS_TO_NSFW_DETECT_SERVICE }}
          HOT_OR_NOT_ALLOYDB_INSTANCE: ${{ secrets.HOT_OR_NOT_ALLOYDB_INSTANCE }}
          HOT_OR_NOT_ALLOYDB_DB_PASSWORD: ${{ secrets.HOT_OR_NOT_ALLOYDB_DB_PASSWORD }}
          HOT_OR_NOT_ALLOYDB_SERVICE_ACCOUNT: ${{ secrets.HOT_OR_NOT_ALLOYDB_SERVICE_ACCOUNT }}
          HOT_OR_NOT_WORKER_JWT: ${{ secrets.HOT_OR_NOT_WORKER_JWT }}
          YRAL_AUTH_V2_PREVIEW_SECRET_KEY: ${{ secrets.YRAL_AUTH_V2_PREVIEW_SECRET_KEY }}
          ANALYTICS_SERVER_TOKEN: ${{ secrets.ANALYTICS_SERVER_TOKEN }}
          AUTH_JWT_ES256_SIGNING_SECRET_KEY_PEM: ${{ secrets.AUTH_JWT_ES256_SIGNING_SECRET_KEY_PEM }}
          YRAL_METADATA_NOTIFICATION_API_KEY: ${{ secrets.YRAL_METADATA_NOTIFICATION_API_KEY }}
          OTLP_ENDPOINT: ${{ secrets.OTLP_ENDPOINT }}
          STDB_ADMIN_ACCESS_TOKEN: ${{ secrets.STDB_ADMIN_ACCESS_TOKEN }}
        run: |
          vault kv put secret/hot-or-not-web-leptos-ssr/CLOUDFLARE_STREAM_IMAGES_ANALYTICS_READ_WRITE_SECRET value="$CLOUDFLARE_STREAM_IMAGES_ANALYTICS_READ_WRITE_SECRET"
          vault kv put secret/hot-or-not-web-leptos-ssr/YRAL_DAPP_BACKEND_APP_ADMIN_AND_PROPOSAL_SUBMITTER_IDENTITY_PRIVATE_KEY value="$YRAL_DAPP_BACKEND_APP_ADMIN_AND_PROPOSAL_SUBMITTER_IDENTITY_PRIVATE_KEY"
          vault kv put secret/hot-or-not-web-leptos-ssr/AUTH_SESSION_COOKIE_SIGNING_SECRET_KEY value="$AUTH_SESSION_COOKIE_SIGNING_SECRET_KEY"
          vault kv put secret/hot-or-not-web-leptos-ssr/OFF_CHAIN_AGENT_GRPC_AUTH_TOKEN value="$OFF_CHAIN_AGENT_GRPC_AUTH_TOKEN"
          vault kv put secret/hot-or-not-web-leptos-ssr/HOT_OR_NOT_FEED_INTELLIGENCE_FIREBASE_PROJECT_EVENTS_BQ_SERVICE_ACCOUNT_JSON_FOR_WEB_LEPTOS_SSR_APP value="$HOT_OR_NOT_FEED_INTELLIGENCE_FIREBASE_PROJECT_EVENTS_BQ_SERVICE_ACCOUNT_JSON_FOR_WEB_LEPTOS_SSR_APP"
          vault kv put secret/hot-or-not-web-leptos-ssr/QSTASH_TOKEN value="$QSTASH_TOKEN"
          vault kv put secret/hot-or-not-web-leptos-ssr/GOOGLE_ANALYTICS_MEASUREMENT_PROTOCOL_API_SECRET value="$GOOGLE_ANALYTICS_MEASUREMENT_PROTOCOL_API_SECRET"
          vault kv put secret/hot-or-not-web-leptos-ssr/TOKEN_TO_SIGN_OUTGOING_CALLS_TO_NSFW_DETECT_SERVICE value="$TOKEN_TO_SIGN_OUTGOING_CALLS_TO_NSFW_DETECT_SERVICE"
          vault kv put secret/hot-or-not-web-leptos-ssr/HOT_OR_NOT_ALLOYDB_INSTANCE value="$HOT_OR_NOT_ALLOYDB_INSTANCE"
          vault kv put secret/hot-or-not-web-leptos-ssr/HOT_OR_NOT_ALLOYDB_DB_PASSWORD value="$HOT_OR_NOT_ALLOYDB_DB_PASSWORD"
          vault kv put secret/hot-or-not-web-leptos-ssr/HOT_OR_NOT_ALLOYDB_SERVICE_ACCOUNT value="$HOT_OR_NOT_ALLOYDB_SERVICE_ACCOUNT"
          vault kv put secret/hot-or-not-web-leptos-ssr/HOT_OR_NOT_WORKER_JWT value="$HOT_OR_NOT_WORKER_JWT"
          vault kv put secret/hot-or-not-web-leptos-ssr/YRAL_AUTH_V2_PREVIEW_SECRET_KEY value="$YRAL_AUTH_V2_PREVIEW_SECRET_KEY"
          vault kv put secret/hot-or-not-web-leptos-ssr/ANALYTICS_SERVER_TOKEN value="$ANALYTICS_SERVER_TOKEN"
          vault kv put secret/hot-or-not-web-leptos-ssr/AUTH_JWT_ES256_SIGNING_SECRET_KEY_PEM value="$AUTH_JWT_ES256_SIGNING_SECRET_KEY_PEM"
          vault kv put secret/hot-or-not-web-leptos-ssr/YRAL_METADATA_NOTIFICATION_API_KEY value="$YRAL_METADATA_NOTIFICATION_API_KEY"
          vault kv put secret/hot-or-not-web-leptos-ssr/OTLP_ENDPOINT value="$OTLP_ENDPOINT"
          vault kv put secret/hot-or-not-web-leptos-ssr/STDB_ADMIN_ACCESS_TOKEN value="$STDB_ADMIN_ACCESS_TOKEN"