name: Upload secrets to vault

on:
  workflow_dispatch:

permissions:
  id-token: write   
  contents: read

jobs:
  upload-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault.yral.com
          method: jwt
          role: hot-or-not-web-leptos-ssr-write-role
          jwtGithubAudience: "https://github.com/dolr-ai"
          exportToken: true
      
      - name: Install Vault CLI
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vault

      - name: Set Secrets
        env:
          VAULT_ADDR: https://vault.yral.com
          CF_TOKEN: ${{ secrets.CLOUDFLARE_STREAM_IMAGES_ANALYTICS_READ_WRITE_SECRET }}
          BACKEND_ADMIN_IDENTITY: ${{ secrets.YRAL_DAPP_BACKEND_APP_ADMIN_AND_PROPOSAL_SUBMITTER_IDENTITY_PRIVATE_KEY }}
          COOKIE_KEY: ${{ secrets.AUTH_SESSION_COOKIE_SIGNING_SECRET_KEY }}
          GRPC_AUTH_TOKEN: ${{ secrets.OFF_CHAIN_AGENT_GRPC_AUTH_TOKEN }}
          HON_GOOGLE_SERVICE_ACCOUNT: ${{ secrets.HOT_OR_NOT_FEED_INTELLIGENCE_FIREBASE_PROJECT_EVENTS_BQ_SERVICE_ACCOUNT_JSON_FOR_WEB_LEPTOS_SSR_APP }}
          QSTASH_TOKEN: ${{ secrets.QSTASH_TOKEN }}
          GA4_API_SECRET: ${{ secrets.GOOGLE_ANALYTICS_MEASUREMENT_PROTOCOL_API_SECRET }}
          NSFW_GRPC_TOKEN: ${{ secrets.TOKEN_TO_SIGN_OUTGOING_CALLS_TO_NSFW_DETECT_SERVICE }}
          ALLOYDB_INSTANCE: ${{ secrets.HOT_OR_NOT_ALLOYDB_INSTANCE }}
          ALLOYDB_DB_PASSWORD: ${{ secrets.HOT_OR_NOT_ALLOYDB_DB_PASSWORD }}
          ALLOYDB_SERVICE_ACCOUNT_JSON: ${{ secrets.HOT_OR_NOT_ALLOYDB_SERVICE_ACCOUNT }}
          HON_WORKER_JWT: ${{ secrets.HOT_OR_NOT_WORKER_JWT }}
          YRAL_AUTH_CLIENT_SECRET: ${{ secrets.YRAL_AUTH_V2_PREVIEW_SECRET_KEY }}
          ANALYTICS_SERVER_TOKEN: ${{ secrets.ANALYTICS_SERVER_TOKEN }}
          YRAL_AUTH_MIGRATION_ES256_PEM: ${{ secrets.AUTH_JWT_ES256_SIGNING_SECRET_KEY_PEM }}
          YRAL_METADATA_NOTIFICATION_API_KEY: ${{ secrets.YRAL_METADATA_NOTIFICATION_API_KEY }}
          OTLP_ENDPOINT: ${{ secrets.OTLP_ENDPOINT }}
          DRAGONFLY_PASSWORD: ${{ secrets.DRAGONFLY_PASSWORD }}
          DRAGONFLY_HOSTS: ${{ vars.DRAGONFLY_HOSTS }}
          DRAGONFLY_CA_CERT: ${{ secrets.DRAGONFLY_CA_CERT }}
          DRAGONFLY_CLIENT_CERT: ${{ secrets.DRAGONFLY_CLIENT_CERT }}
          DRAGONFLY_CLIENT_KEY: ${{ secrets.DRAGONFLY_CLIENT_KEY }}
        run: |
          vault kv put secret/hot-or-not-web-leptos-ssr/CF_TOKEN value="$CF_TOKEN" \
          vault kv put secret/hot-or-not-web-leptos-ssr/BACKEND_ADMIN_IDENTITY value="$BACKEND_ADMIN_IDENTITY" \
          vault kv put secret/hot-or-not-web-leptos-ssr/COOKIE_KEY value="$COOKIE_KEY" \
          vault kv put secret/hot-or-not-web-leptos-ssr/GRPC_AUTH_TOKEN value="$GRPC_AUTH_TOKEN" \
          vault kv put secret/hot-or-not-web-leptos-ssr/HON_GOOGLE_SERVICE_ACCOUNT value="$HON_GOOGLE_SERVICE_ACCOUNT" \
          vault kv put secret/hot-or-not-web-leptos-ssr/QSTASH_TOKEN value="$QSTASH_TOKEN" \
          vault kv put secret/hot-or-not-web-leptos-ssr/GA4_API_SECRET value="$GA4_API_SECRET" \
          vault kv put secret/hot-or-not-web-leptos-ssr/NSFW_GRPC_TOKEN value="$NSFW_GRPC_TOKEN" \
          vault kv put secret/hot-or-not-web-leptos-ssr/ALLOYDB_INSTANCE value="$ALLOYDB_INSTANCE" \
          vault kv put secret/hot-or-not-web-leptos-ssr/ALLOYDB_DB_PASSWORD value="$ALLOYDB_DB_PASSWORD" \
          vault kv put secret/hot-or-not-web-leptos-ssr/ALLOYDB_SERVICE_ACCOUNT_JSON value="$ALLOYDB_SERVICE_ACCOUNT_JSON" \
          vault kv put secret/hot-or-not-web-leptos-ssr/HON_WORKER_JWT value="$HON_WORKER_JWT" \
          vault kv put secret/hot-or-not-web-leptos-ssr/YRAL_AUTH_CLIENT_SECRET value="$YRAL_AUTH_CLIENT_SECRET" \
          vault kv put secret/hot-or-not-web-leptos-ssr/ANALYTICS_SERVER_TOKEN value="$ANALYTICS_SERVER_TOKEN" \
          vault kv put secret/hot-or-not-web-leptos-ssr/YRAL_AUTH_MIGRATION_ES256_PEM value="$YRAL_AUTH_MIGRATION_ES256_PEM" \
          vault kv put secret/hot-or-not-web-leptos-ssr/YRAL_METADATA_NOTIFICATION_API_KEY value="$YRAL_METADATA_NOTIFICATION_API_KEY" \
          vault kv put secret/hot-or-not-web-leptos-ssr/OTLP_ENDPOINT value="$OTLP_ENDPOINT" \
          vault kv put secret/hot-or-not-web-leptos-ssr/DRAGONFLY_PASSWORD value="$DRAGONFLY_PASSWORD" \
          vault kv put secret/hot-or-not-web-leptos-ssr/DRAGONFLY_HOSTS value="$DRAGONFLY_HOSTS" \
          vault kv put secret/hot-or-not-web-leptos-ssr/DRAGONFLY_CA_CERT value="$DRAGONFLY_CA_CERT" \
          vault kv put secret/hot-or-not-web-leptos-ssr/DRAGONFLY_CLIENT_CERT value="$DRAGONFLY_CLIENT_CERT" \
          vault kv put secret/hot-or-not-web-leptos-ssr/DRAGONFLY_CLIENT_KEY value="$DRAGONFLY_CLIENT_KEY"  \
          